packages:
  - apps/*
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/effects/*
  - internal/*
  - internal/lint-configs/*
catalog:
  "@commitlint/cli": 19.5.0
  "@commitlint/config-conventional": 19.5.0
  "@eslint/js": ^9.10.0
  "@iconify/vue": 4.1.2
  "@intlify/core-base": 10.0.4
  "@intlify/unplugin-vue-i18n": 5.2.0
  "@manypkg/get-packages": 2.2.2
  "@radix-icons/vue": 1.0.0
  "@tailwindcss/nesting": 0.0.0-insiders.565cd3e
  "@tanstack/vue-store": 0.5.7
  "@types/eslint": 9.6.1
  "@types/lodash": 4.17.15
  "@types/node": ^20.14.5
  "@typescript-eslint/eslint-plugin": 8.4.0
  "@typescript-eslint/parser": 8.6.0
  "@vee-validate/zod": 4.15.0
  "@vitejs/plugin-vue": 5.1.4
  "@vue/shared": 3.5.13
  "@vueuse/core": 11.2.0
  autoprefixer: 10.4.20
  class-variance-authority: 0.7.0
  clsx: 2.1.1
  commitlint-plugin-function-rules: 4.0.0
  cssnano: 7.0.6
  czg: ^1.9.4
  defu: 6.1.4
  dotenv: 16.4.5
  element-plus: 2.8.6
  eslint: ^8.57.0
  eslint-plugin-command: 0.2.4
  eslint-plugin-import-x: 4.2.1
  eslint-plugin-jsonc: ^2.16.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-unused-imports: 4.1.3
  eslint-plugin-vue: ^9.23.0
  find-up: 7.0.0
  globals: ^15.9.0
  husky: 9.1.6
  jsonc-eslint-parser: ^2.4.0
  lint-staged: 15.2.10
  lodash: 4.17.21
  lucide-vue-next: 0.454.0
  pinia: ^2.1.7
  postcss: 8.4.47
  postcss-html: 1.7.0
  postcss-import: 16.1.0
  postcss-scss: 4.0.9
  prettier: 3.3.3
  prettier-plugin-tailwindcss: 0.6.8
  radix-vue: 1.9.8
  rollup-plugin-visualizer: 5.12.0
  stylelint: 16.9.0
  stylelint-config-recess-order: 5.1.0
  stylelint-config-recommended-scss: 14.1.0
  stylelint-config-recommended-vue: 1.5.0
  stylelint-config-standard: 36.0.1
  stylelint-order: 6.0.4
  stylelint-prettier: 5.0.2
  stylelint-scss: 6.7.0
  tailwind-merge: 2.5.4
  tailwindcss-animate: 1.0.7
  turbo: ^2.1.1
  typescript: ^5.6.3
  typescript-eslint: ^8.4.0
  unbuild: 2.0.0
  unplugin-element-plus: 0.8.0
  vee-validate: 4.15.0
  vite: ^5.3.1
  vite-plugin-dts: 4.2.3
  vite-plugin-html: 3.2.2
  vite-plugin-vue-devtools: 7.4.6
  vue: 3.5.13
  vue-eslint-parser: ^9.4.3
  vue-i18n: 10.0.4
  vue-router: ^4.3.3
  vue-tsc: ^2.1.6
  zod: 3.23.8
  zod-defaults: 0.1.3
